export const CREATE_PUBLICATION_START = 'CREATE_PUBLICATION_START';
export const CREATE_PUBLICATION_STOP = 'CREATE_PUBLICATION_STOP';
export const UPLOAD_IMAGE_PROGRESS = 'UPLOAD_IMAGE_PROGRESS';
export const CHANGE_PUBLICATION_FORM = 'CHANGE_PUBLICATION_FORM';